---
title: "datasci_exam"
output: html_document
date: "2023-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse,tsibble, ggfortify, feasts, ggplot2, gridExtra, fable, patchwork, Metrics)
```

loading data and cleaning

```{r}
# data path
data_path <- "../data/top_songs_by_month.csv"

# read to dataframe
df <- read_csv(data_path)

# df_ts <- as_tsibble(df, key = song_name, index = date) # time series tibble

```

```{r}

# aggregate by month
df_agg <- df %>% 
  group_by(date) %>% 
  summarize(dance_mean = mean(danceability),
            energy_mean = mean(energy),
            speechiness_mean = mean(speechiness),
            acousticness_mean = mean(acousticness),
            instrumentalness_mean = mean(instrumentalness),
            liveness_mean = mean(liveness),
            valence_mean = mean(valence),
            ) 

# correct date formatting 
df_agg <- df_agg %>% 
  mutate(month = yearmonth(date))

# time series tibble
df_ts_agg <- as_tsibble(df_agg, index = month)

# define color palette
colors = c("deeppink", "red4", "gold1", "seagreen3", "darkorange", "darkorchid")

# long format
df_agg_long <- df_agg %>% 
  pivot_longer(., -c('month', 'date'))

# plot audio features
df_agg_long %>% 
  filter(name != "liveness_mean") %>% 
  ggplot(aes(x = date, y = value, col = name))+
  geom_line()+
  facet_grid(~name)+
  theme_bw()+
  theme(legend.position = "none")+
  scale_color_manual(values = colors)
```


```{r}
# define autocorrelation plotting function
plot_acf <- function(variable, title, color) {
  
  df_ts_agg %>%
    ACF(variable, lag_max = 756) %>%
    autoplot() +
    geom_line(color = color) +
    geom_area(fill = color) +
    geom_hline(yintercept = 0, color = "black") +
    geom_hline(yintercept = 0.071, linetype = "dashed", color = "black") +
    geom_hline(yintercept = -0.071, linetype = "dashed", color = "black") +
    theme_bw() +
    theme(axis.title.x = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
    scale_x_continuous(breaks = seq(0, 756, 12)) +
    geom_vline(xintercept = 240, col = 'darkgrey', linetype = "dashed") +
    ggtitle(title)
}

# make plot for each audio feature
p1 <- plot_acf(df_ts_agg$dance_mean, "Danceability autocorrelation", "red4")
p2 <- plot_acf(df_ts_agg$energy_mean, "Energy autocorrelation", "gold1")
p3 <- plot_acf(df_ts_agg$speechiness_mean, "Speechiness autocorrelation", "darkorange")
p4 <- plot_acf(df_ts_agg$dance_mean, "Acousticness autocorrelation", "deeppink")
p5 <- plot_acf(df_ts_agg$energy_mean, "Instrumentalness autocorrelation", "seagreen3")
p6 <- plot_acf(df_ts_agg$speechiness_mean, "Valence autocorrelation", "darkorchid")

# combine using patchwork
(p4+p1)/(p2+p5)/(p3+p6)

```



```{r}
# define seasonal-trend decomposition plotting function
stl_plot <- function(variable, nplot){
  p <- df_ts_agg %>% 
    model(STL(variable ~ trend(window = 35) + season(window = "periodic"),
              robust = T)) %>% 
    components() %>% 
    autoplot()+
    theme_bw()
  
  # Modify the color of the plot
  p_build <- ggplot_build(p)
  p_build$data[[1]]$colour <- colors[nplot]
  p_gtable <- ggplot_gtable(p_build)
  grid.arrange(p_gtable)
}

# make stl plot for each audio feature
stl_plot(df_ts_agg$acousticness_mean, 1)
stl_plot(df_ts_agg$dance_mean, 2)
stl_plot(df_ts_agg$energy_mean, 3)
stl_plot(df_ts_agg$instrumentalness_mean, 4)
stl_plot(df_ts_agg$valence_mean, 5)
stl_plot(df_ts_agg$speechiness_mean, 6)

```


fourier components, harmonic regression
```{r}
# Split data into training and test sets
train <- head(df_ts_agg, -120) # corresponding to 10 years
test <- tail(df_ts_agg, 120)

```


```{r}
# modelling using fourier 
model_function <- function(variable){
  fit <- train %>% 
    
  model(k20_p120 <-  TSLM(variable~trend() + fourier(K = 20, period = 120)), # 10 year period
        k30_p120 <-  TSLM(variable~trend() + fourier(K = 30, period = 120)),
        k60_p120 <-  TSLM(variable~trend() + fourier(K = 60, period = 120)),
        
        k30_p240 <-  TSLM(variable~trend() + fourier(K = 30, period = 240)), # 20 year period
        k60_p240 <-  TSLM(variable~trend() + fourier(K = 60, period = 240)),
        k120_p240 <-  TSLM(variable~trend() + fourier(K = 120, period = 240)),
        
        k30_p300 <-  TSLM(variable~trend() + fourier(K = 40, period = 300)), # 25 year period
        k60_p300 <-  TSLM(variable~trend() + fourier(K = 80, period = 300)),
        k150_p300 <-  TSLM(variable~trend() + fourier(K = 120, period = 300)),
        
        # with seasonality as predictor:
        
        sk20_p120 <-  TSLM(variable~trend() + season() +fourier(K = 20, period = 120)), # 10 year period
        sk30_p120 <-  TSLM(variable~trend() + season() +fourier(K = 30, period = 120)),
        sk60_p120 <-  TSLM(variable~trend() + season() +fourier(K = 60, period = 120)),
        
        sk30_p240 <-  TSLM(variable~trend() + season() +fourier(K = 30, period = 240)), # 20 year period
        sk60_p240 <-  TSLM(variable~trend() +season() + fourier(K = 60, period = 240)),
        sk120_p240 <-  TSLM(variable~trend() + season() +fourier(K = 120, period = 240)),
        
        sk30_p300 <-  TSLM(variable~trend() +season() + fourier(K = 40, period = 300)), # 25 year period
        sk60_p300 <-  TSLM(variable~trend() + season() +fourier(K = 80, period = 300)),
        sk150_p300 <-  TSLM(variable~trend() +season() + fourier(K = 120, period = 300)),

        )
  return (fit)
}

# fit model for each of the audio features
dance_fit <- model_function(train$dance_mean) # daceability
energy_fit <- model_function(train$energy_mean) # energy
speech_fit <- model_function(train$speechiness_mean) # speechiness
acoust_fit <- model_function(train$acousticness_mean) # acousticness
instru_fit <- model_function(train$instrumentalness_mean) # instrumentalness
val_fit <- model_function(train$valence_mean) # valence


# make model comparison dataframes for each audio feature
dancedf <- glance(dance_fit) %>% select(.model, r_squared, adj_r_squared, AIC, AICc)
energydf <- glance(energy_fit) %>% select(.model, r_squared, adj_r_squared, AIC, AICc)
speechdf <- glance(speech_fit) %>% select(.model, r_squared, adj_r_squared, AIC, AICc)
acoustdf <- glance(acoust_fit) %>% select(.model, r_squared, adj_r_squared, AIC, AICc)
intrudf <- glance(instru_fit) %>% select(.model, r_squared, adj_r_squared, AIC, AICc)
valdf <- glance(val_fit) %>% select(.model, r_squared, adj_r_squared, AIC, AICc)

```

residuals 
```{r}
dance_fit %>% residuals() %>% 
  ggplot() + 
  geom_point(aes(x = month, y = .resid)) +
  facet_wrap(~.model)
```

```{r}
# modelling using fourier 
model_function <- function(variable){
  fit <- train %>% 
    
  model(k20_p120 <-  TSLM(variable~trend() + fourier(K = 20, period = 120)), # 10 year period
        k30_p120 <-  TSLM(variable~trend() + fourier(K = 30, period = 120)),
        k60_p120 <-  TSLM(variable~trend() + fourier(K = 60, period = 120)),
        
        k30_p240 <-  TSLM(variable~trend() + fourier(K = 30, period = 240)), # 20 year period
        k60_p240 <-  TSLM(variable~trend() + fourier(K = 60, period = 240)),
        k120_p240 <-  TSLM(variable~trend() + fourier(K = 120, period = 240)),
        
        k30_p300 <-  TSLM(variable~trend() + fourier(K = 40, period = 300)), # 25 year period
        k60_p300 <-  TSLM(variable~trend() + fourier(K = 80, period = 300)),
        k150_p300 <-  TSLM(variable~trend() + fourier(K = 120, period = 300)),
        
        max1 <- TSLM(variable~trend() + fourier(K = 20, period = 120) + 
                       fourier(K = 60, period = 120)+
                       fourier(K = 30, period = 240)+ 
                       fourier(K = 120, period = 240)+
                       fourier(K = 40, period = 300)+
                       fourier(K = 120, period = 300))

        )
  return (fit)
}

# fit model for each of the audio features
dance_fit <- model_function(train$dance_mean) # daceability

dance_fit %>% residuals() %>% 
  ggplot() + 
  geom_point(aes(x = month, y = .resid)) +
  facet_wrap(~.model)

dance_fit %>% select("max1 <- TSLM(variable ~ trend() + fourier(K = 20, period = 120) + \n    fourier(K = 60, period = 120) + fourier(K = 30, period = 240) + \n    fourier(K = 120, period = 240) + fourier(K = 40, period = 300) + \n    fourier(K = 120, period = 300))") %>% 
  gg_tsresiduals()

dance_fit %>% glance()
```


make predictions from training data

```{r}
# danceability
pred_dance <- train %>% 
  model(fit <- TSLM(dance_mean~trend() + fourier(K = 30, period = 240))) %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# energy
pred_energy <- train %>% 
  model(fit <- TSLM(energy_mean~trend() + fourier(K = 30, period = 240))) %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# speechiness
pred_speech <- train %>% 
  model(fit <- TSLM(speechiness_mean~trend() + fourier(K = 30, period = 240))) %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# acousticness
pred_acous <- train %>% 
  model(fit <- TSLM(acousticness_mean~trend() + fourier(K = 30, period = 240))) %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# instrumentalness
pred_instru <- train %>% 
  model(fit <- TSLM(instrumentalness_mean~trend() + fourier(K = 30, period = 240))) %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# valence 
pred_valence <- train %>% 
  model(fit <- TSLM(valence_mean~trend() + fourier(K = 30, period = 240))) %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")


```

plot training predictions against real test data

```{r}
# plot danceability
t1 <- train %>% 
  ggplot()+ 
  geom_line(data = train, aes(x = month, y = dance_mean))+
  geom_ribbon(data = pred_dance, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.3, fill = 'salmon3')+
  geom_ribbon(data = pred_dance, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.5, fill = 'salmon')+
  geom_line(data = test, aes(x = month, y = dance_mean), alpha = 1, col = 'grey49')+
  geom_line(data = pred_dance, aes(x = month, y = .mean), col = 'red4', size = 0.6)+
  theme_bw()+
  ylab("")+
  xlab("")+
  ggtitle("Danceability, prediction compared to test data")+
  theme(legend.position = "none")


# plot energy
t2 <- train %>% 
  ggplot()+
  geom_line(data = train, aes(x = month, y = energy_mean))+
  geom_ribbon(data = pred_energy, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'gold1')+
  geom_ribbon(data = pred_energy, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'gold')+
  geom_line(data = test, aes(x = month, y = energy_mean), alpha = .9, col = 'grey51')+
  geom_line(data = pred_energy, aes(x = month, y = .mean), col = 'gold3', size = 0.7)+
  theme_bw()+
    ylab("")+
  xlab("")+
  ggtitle("Energy, prediction compared to test data")+
  theme(legend.position = "none")


# plot speechiness
t3 <- train %>% 
  ggplot()+
  geom_line(data = train, aes(x = month, y = speechiness_mean))+
  geom_ribbon(data = pred_speech, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'darkorange')+
  geom_ribbon(data = pred_speech, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'darkorange')+
  geom_line(data = test, aes(x = month, y = speechiness_mean), alpha = .8, col = 'grey49')+
  geom_line(data = pred_speech, aes(x = month, y = .mean), col = 'darkorange3', size = 0.7)+
  theme_bw()+
    ylab("")+
  xlab("")+
  ggtitle("Speechiness, prediction compared to test data")+
  theme(legend.position = "none")

# plot acousticness
t4 <- train %>% 
  ggplot()+
  geom_line(data = train, aes(x = month, y = acousticness_mean))+
  geom_ribbon(data = pred_acous, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'deeppink')+
  geom_ribbon(data = pred_acous, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'deeppink')+
  geom_line(data = test, aes(x = month, y = acousticness_mean), alpha = .8, col = 'grey49')+
  geom_line(data = pred_acous, aes(x = month, y = .mean), col = 'deeppink', size = 0.7)+
  theme_bw()+
    ylab("")+
  xlab("")+
  ggtitle("Acousticness, prediction compared to test data")+
  theme(legend.position = "none")

# plot instrumentalness
t5 <- train %>% 
 ggplot()+
  geom_line(data = train, aes(x = month, y = instrumentalness_mean))+
  geom_ribbon(data = pred_instru, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'seagreen3')+
  geom_ribbon(data = pred_instru, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'seagreen3')+
  geom_line(data = test, aes(x = month, y = instrumentalness_mean), alpha = .8, col = 'grey49')+
  geom_line(data = pred_instru, aes(x = month, y = .mean), col = 'darkgreen', size = 0.6)+
  theme_bw()+
    ylab("")+
  xlab("")+
  ggtitle("Instrumentalness, prediction compared to test data")+
  theme(legend.position = "none")

# plot valence
t6 <- train %>% 
 ggplot()+
  geom_line(data = train, aes(x = month, y = valence_mean))+
  geom_ribbon(data = pred_valence, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'darkorchid')+
  geom_ribbon(data = pred_valence, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'darkorchid')+
  geom_line(data = test, aes(x = month, y = valence_mean), alpha = .8, col = 'grey47')+
  geom_line(data = pred_valence, aes(x = month, y = .mean), col = 'darkorchid4', size = 0.6)+
  theme_bw()+
    ylab("")+
  xlab("")+
  ggtitle("Valence, prediction compared to test data")+
  theme(legend.position = "none")

# combine using patchwork
(t4+t1)/(t2+t5)/(t3+t6)


```



get measure for how accurate the predictions were: mae and rmse

```{r}
# clean up forecast dfs to make comparable
pred_dance_df <- as.data.frame(pred_dance) %>% 
  select(c('.mean', 'month')) %>% 
  rename(pred_mean = '.mean') %>% 
  cbind(test$dance_mean) %>% 
  rename(mean = 'test$dance_mean')

pred_acous_df <- as.data.frame(pred_acous) %>% 
  select(c('.mean', 'month')) %>% 
  rename(pred_mean = '.mean') %>% 
  cbind(test$acousticness_mean) %>% 
  rename(mean = 'test$acousticness_mean')

pred_energy_df <- as.data.frame(pred_acous) %>% 
  select(c('.mean', 'month')) %>% 
  rename(pred_mean = '.mean') %>% 
  cbind(test$energy_mean) %>% 
  rename(mean = 'test$energy_mean')

pred_instru_df <- as.data.frame(pred_instru) %>% 
  select(c('.mean', 'month')) %>% 
  rename(pred_mean = '.mean') %>% 
  cbind(test$instrumentalness_mean) %>% 
  rename(mean = 'test$instrumentalness_mean')

pred_speech_df <- as.data.frame(pred_speech) %>% 
  select(c('.mean', 'month')) %>% 
  rename(pred_mean = '.mean') %>% 
  cbind(test$speechiness_mean) %>% 
  rename(mean = 'test$speechiness_mean')

pred_valence_df <- as.data.frame(pred_valence) %>% 
  select(c('.mean', 'month')) %>% 
  rename(pred_mean = '.mean') %>% 
  cbind(test$valence_mean) %>% 
  rename(mean = 'test$valence_mean')

# calculate mean absolute error and root mean square error for each audio feature
dance_mae <- mae(pred_dance_df$pred_mean, pred_dance_df$mean)
dance_rmse <- rmse(pred_dance_df$pred_mean, pred_dance_df$mean)

acous_mae <- mae(pred_acous_df$pred_mean, pred_acous_df$mean)
acous_rmse <- rmse(pred_acous_df$pred_mean, pred_acous_df$mean)

energy_mae <- mae(pred_energy_df$pred_mean, pred_energy_df$mean)
energy_rmse <- rmse(pred_energy_df$pred_mean, pred_energy_df$mean)

instru_mae <- mae(pred_instru_df$pred_mean, pred_instru_df$mean)
instru_rmse <- rmse(pred_instru_df$pred_mean, pred_instru_df$mean)

speech_mae <- mae(pred_speech_df$pred_mean, pred_speech_df$mean)
speech_rmse <- rmse(pred_speech_df$pred_mean, pred_speech_df$mean)

valence_mae <- mae(pred_valence_df$pred_mean, pred_valence_df$mean)
valence_rmse <- rmse(pred_valence_df$pred_mean, pred_valence_df$mean)
```

overview of prediction accuracy continued
```{r}
# create vectors for each measure
mae <- c(dance_mae, acous_mae, energy_mae, instru_mae, speech_mae, valence_mae)
rmse <- c(dance_rmse, acous_rmse, energy_rmse, instru_rmse, speech_rmse, valence_rmse)

# create df
error_overview <- data.frame(feature = c("Danceability", "Acousticness", "Energy", "Instrumentalness", "Speechiness", "Valence"),
                 mae = mae,
                 rmse = rmse)

# make long format before plotting
error_overview_long <- pivot_longer(
  data = error_overview,
  cols = c("mae", "rmse"),
  names_to = "error_type",
  values_to = "error_value"
)


# no longer the ugliest plot in the world
ggplot(error_overview_long, aes(x = feature, y = error_value, color = error_type)) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0), size = 4, aes(shape = feature)) +
  ylab("Error") +
  ggtitle("MAE and RMSE by audio feature") +
  theme_bw()+
  scale_shape_discrete(name  ="Error type",
                           breaks=c("mae", "rmse"),
                           labels=c("MAE", "RMSE"))+
  scale_color_brewer(palette = 'Set2',
                     name = "Error type",
                     labels = c("MAE", "RMSE"))+
  xlab("")+
  scale_y_continuous(limits=c(0, 0.65))


```


forecast using full dataset -- what will the future look like?

```{r}
# f1 <- df_ts_agg %>% 
#   model(m1 <- TSLM(dance_mean~trend() + fourier(K = 30, period = 240))) %>% 
#   forecast(h = 120) %>% 
#   autoplot(df_ts_agg, color = "red4")+
#   theme_bw()+
#   theme(legend.position = "none")+
#   ggtitle("Danceability, 10 year prediction")+
#   ylab("")+
#   xlab("")
# f1
```

```{r}
# danceability fit
dance_fit <- df_ts_agg %>% 
  model(m1 <- TSLM(dance_mean~trend() + fourier(K = 30, period = 240)))

# danceability forecast
f_dance <- dance_fit %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# danceability forecast plotted
f1 <- df_ts_agg %>% 
  ggplot()+
  geom_line(aes(x = month, y = dance_mean), alpha = 0.9, col = 'darkgrey')+
  geom_line(data = fitted(dance_fit), aes(x= month, y = .fitted), col = 'red4')+
  geom_ribbon(data = f_dance, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.3, fill = 'salmon3')+
  geom_ribbon(data = f_dance, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.5, fill = 'salmon')+
  geom_line(data = f_dance, aes(x = month, y = .mean),col = 'red4')+
    theme_bw()+
  theme(legend.position = "none")+
  ggtitle("Danceability, model fit and 10 year prediction")+
  ylab("")+
  xlab("")
  
f1
```

```{r}
# acousticness fit
acoust_fit <- df_ts_agg %>% 
  model(m1 <- TSLM(acousticness_mean~trend() + fourier(K = 20, period = 120)))

# acousticness forecast
f_acous <- acoust_fit %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# acousticness forecast plotted
f2 <- df_ts_agg %>% 
  ggplot()+
  geom_line(aes(x = month, y = acousticness_mean), alpha = 0.9, col = 'darkgrey')+
  geom_line(data = fitted(acoust_fit), aes(x= month, y = .fitted), col = 'deeppink')+
      geom_ribbon(data = f_acous, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'deeppink')+
  geom_ribbon(data = f_acous, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.3, fill = 'deeppink')+
  geom_line(data = f_acous, aes(x = month, y = .mean),col = 'deeppink')+
    theme_bw()+
  theme(legend.position = "none")+
  ggtitle("Acousticness, model fit and 10 year forecast")+
  ylab("")+
  xlab("")

f2
```

```{r}
# instrumentalness fit
instru_fit <- df_ts_agg %>% 
  model(m1 <- TSLM(instrumentalness_mean~trend() + fourier(K = 20, period = 120)))

# instrumentalness forecast
f_instru <- instru_fit %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# instrumentalness forecast plotted
f3 <- df_ts_agg %>% 
  ggplot()+
  geom_line(aes(x = month, y = instrumentalness_mean), alpha = 0.7, col = 'darkgrey')+
  geom_line(data = fitted(instru_fit), aes(x= month, y = .fitted), col = 'seagreen')+
      geom_ribbon(data = f_instru, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'seagreen3')+
  geom_ribbon(data = f_instru, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'seagreen3')+
  geom_line(data = f_instru, aes(x = month, y = .mean),col = 'seagreen')+
    theme_bw()+
  theme(legend.position = "none")+
  ggtitle("Instrumentalness, model fit and 10 year forecast")+
  ylab("")+
  xlab("")

f3
```


```{r}
# energy fit
energy_fit <- df_ts_agg %>% 
  model(m1 <- TSLM(energy_mean~trend() + fourier(K = 30, period = 240)))

# energy forecast
f_energy <- energy_fit %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# energy forecast plotted
f4 <- df_ts_agg %>% 
  ggplot()+
  geom_line(aes(x = month, y = energy_mean), alpha = 0.8, col = 'darkgrey')+
  geom_line(data = fitted(energy_fit), aes(x= month, y = .fitted), col = 'gold1', size = 0.7)+
      geom_ribbon(data = f_energy, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'gold1')+
  geom_ribbon(data = f_energy, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'gold1')+
  geom_line(data = f_energy, aes(x = month, y = .mean),col = 'gold1', size = 0.7)+
    theme_bw()+
  theme(legend.position = "none")+
  ggtitle("Energy, model fit and 10 year forecast")+
  ylab("")+
  xlab("")

f4
```

```{r}
# speechiness fit
speech_fit <- df_ts_agg %>% 
  model(m1 <- TSLM(speechiness_mean~trend() + fourier(K = 20, period = 120)))

# speechiness forecast
f_speech <- speech_fit %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# speechiness forecast plotted
f5 <- df_ts_agg %>% 
  ggplot()+
  geom_line(aes(x = month, y = speechiness_mean), alpha = 0.7, col = 'darkgrey')+
  geom_line(data = fitted(speech_fit), aes(x= month, y = .fitted), col = 'darkorange3')+
      geom_ribbon(data = f_speech, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'darkorange')+
  geom_ribbon(data = f_speech, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'darkorange')+
  geom_line(data = f_speech, aes(x = month, y = .mean),col = 'darkorange2')+
    theme_bw()+
  theme(legend.position = "none")+
  ggtitle("Speechiness, model fit and 10 year forecast")+
  ylab("")+
  xlab("")

f5
```



```{r}
# valence fit
val_fit <- df_ts_agg %>% 
  model(m1 <- TSLM(valence_mean~trend() + fourier(K = 20, period = 120)))

# valence forecast
f_val <- val_fit %>% 
  forecast(h = 120) %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo(c('80%', '95%'), names_sep = "_", names_repair = "universal")

# valence forecast plotted
f6 <- df_ts_agg %>% 
  ggplot()+
  geom_line(aes(x = month, y = valence_mean), alpha = 0.7, col = 'darkgrey')+
  geom_line(data = fitted(val_fit), aes(x= month, y = .fitted), col = 'darkorchid')+
      geom_ribbon(data = f_val, aes(x = month, ymin = ..95._lower, ymax = ..95._upper ),
              alpha = 0.2, fill = 'darkorchid')+
  geom_ribbon(data = f_val, aes(x = month, ymin = ..80._lower, ymax = ..80._upper ),
              alpha = 0.4, fill = 'darkorchid')+
  geom_line(data = f_val, aes(x = month, y = .mean),col = 'darkorchid')+
    theme_bw()+
  theme(legend.position = "none")+
  ggtitle("Valence, model fit and 10 year forecast")+
  ylab("")+
  xlab("")

f6
```

```{r}
# plotted together with patchwork
(f2+f1)/(f4+f3)/(f5+f6)
```

